name: flutter_mks_app
description: "A new Flutter project."
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  http: ^1.3.0
  dio: ^5.8.0+1
  carousel_slider: ^5.0.0
  cupertino_icons: ^1.0.8
  shared_preferences: ^2.5.3
  intl: ^0.18.0
  provider: ^6.1.1
  fl_chart: ^0.63.0
  url_launcher: ^6.3.1
  timezone: ^0.10.1
  flutter_native_splash: ^2.4.6
  flutter_launcher_icons: "^0.14.3"
  flutter_local_notifications: ^19.2.1
  permission_handler: ^11.0.1
  google_fonts: ^6.2.1
  firebase_core: ^3.13.1
  firebase_messaging: ^15.2.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_svg: ^2.0.7

  flutter_lints: ^5.0.0

flutter_native_splash:
  image: assets/logo_qualle_condo.png
  background_image: "assets/logo_qualle_condo.png"
  android: true
  ios: true

flutter_icons:
  background_image: "assets/logo_qualle_condo.png"
  android: "launcher_icon"
  ios: true
  remove_alpha_ios: true
  adaptive_icon_foreground: "assets/logo_qualle_condo.png"

flutter:
  uses-material-design: true
  assets:
    - assets/qualle_control.svg
    - assets/ehoteste.png
    - assets/simbolo-azas.png
    - assets/simbolo-cond.png
    - assets/simbolo-hidro.png
    - assets/simbolo-sanea.png
    - assets/prédios_Prancheta.png
    - assets/quallecond.png
    - assets/casas.png
    - assets/bomb1.png
