name: flutter_mks_app
description: "A new Flutter project."
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  http: ^1.3.0
  dio: ^5.8.0+1
  carousel_slider: ^5.0.0
  cupertino_icons: ^1.0.8
  shared_preferences: ^2.5.3
  intl: ^0.18.0
  provider: ^6.1.1
  fl_chart: ^0.63.0
  url_launcher: ^6.3.1
  timezone: ^0.10.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_svg: ^2.0.7

  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/qualle_control.svg
    - assets/ehoteste.png
    - assets/simbolo-azas.png
    - assets/simbolo-cond.png
    - assets/simbolo-hidro.png
    - assets/simbolo-sanea.png
    - assets/prédios_Prancheta.png
    - assets/casas.png
